### ISSUE TITLE
Mobile doesn't work 

### ISSUE THREAD

**Issue by rvolyar** [AbhinavMadahar/Presentador#1]
Fix the site on mobile browsers

**Comment by AbhinavMadahar** [comment]
Are you on Wifi or mobile data?

**Comment by rvolyar** [comment]
Wifi but i dont think that should matter.

**Comment by AbhinavMadahar** [comment]
It might. That said, there is a known bug in which slides aren't added if you're using HTTPS. I'll fix that eventually, but make sure that you're not using HTTPS for now

**Comment by AbhinavMadahar** [comment]
Also, it does not work correctly on my phone either (Chrome for Android 5.1). Let me try to fix this

**Comment by AbhinavMadahar** [comment]
Does it work now for you? It works on every device I have.

**Comment by rvolyar** [comment]
Yea it works but still buggy and slow
