### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by rvolyar** [AbhinavMadahar/Presentador#5]
Put the name of the site in the top left, and the actual search field with make presentation button in the middle.  The results should autocomplete as you type. Once you select a result, the language field should be auto populated  with the available languages the article is available in.   By default it should be preselected as english.  Possibly add full screen mode. Make a menu, (possibly hamburger) to hide your links. Add share buttons that generate a link to the unique presentation.  More thoughts to come..

**Comment by AbhinavMadahar** [comment]
I'm using Reveal.js to handle the presentation for the most part, and forms
inside the slide are probably not going to work well
