### ISSUE TITLE
menubar dissapears

### ISSUE THREAD

**Issue by rvolyar** [AbhinavMadahar/Presentador#6]
if you click on the menubar, the button disappears and you can't hide it again.

**Comment by AbhinavMadahar** [comment]
Yeah you're supposed to press backslash to make it disappear. I suppose
some sort of note would be helpful

**Comment by rvolyar** [comment]
Maybe the menubar button should change to an x icon when clicked on..?

**Comment by AbhinavMadahar** [comment]
Fixed
