### ISSUE TITLE
change url unique to each article

### ISSUE THREAD

**Issue by rvolyar** [AbhinavMadahar/Presentador#7]
you can use the history api for this.  This wont refresh the page

**Comment by AbhinavMadahar** [comment]
As it currently is, [presentador.co/Germany](http://presentador.co/Germany) would make a presentation for Germany, and so forth. Is that what you mean?

**Comment by rvolyar** [comment]
Sort of. If i click your link, and then want to make a new presentation
about reddit, I as a user get no response from the site. Ideally, it should
delete the germany slides, load the reddit ones and change the url of the
page to presentador.co/reddit using the history api.

https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history

**Comment by AbhinavMadahar** [comment]
It injects the slides into the presentations at the end, right? That's what
it should do

**Comment by rvolyar** [comment]
It didnt work for me, and if it does there should be a visual of some sort
to tell the user. But then the "new presentation" button isnt really new.
It justs appends to the presentation.
